### ISSUE TITLE
Branch protection rules seem to auto-protect PR branches

### ISSUE THREAD

**Issue by originalfoo** [Alterran/CS-PropLineTool#8]
It looks like the branch protection rules are auto-protecting PR branches meaning that I can't push more commits to an open PR.

Ideally only the master branch should be protected (to prevent me from committing directly to it; all my contributions must go through PR review process).

Github docs relating to branch protection rules: https://help.github.com/en/articles/configuring-protected-branches

**Comment by Alterran** [comment]
Updated branch protection rules. Now only master branch is protected.
